// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwzijOz4JyymC9Fu1W1WcZc3Lg0UE4ig',
    appId: '1:1019752312959:web:c85a9a09a32d7dc6790f4a',
    messagingSenderId: '1019752312959',
    projectId: 'job-bridge-e885b',
    authDomain: 'job-bridge-e885b.firebaseapp.com',
    storageBucket: 'job-bridge-e885b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjPjmvdWQC2FigEeUXM_uW3XpgnlSEo6w',
    appId: '1:1019752312959:android:2a4f4ae2aca876f6790f4a',
    messagingSenderId: '1019752312959',
    projectId: 'job-bridge-e885b',
    storageBucket: 'job-bridge-e885b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8dAiBBG0pqFCX4E2mtOIs1RMIvhhNCI',
    appId: '1:1019752312959:ios:e79da494b69c31b6790f4a',
    messagingSenderId: '1019752312959',
    projectId: 'job-bridge-e885b',
    storageBucket: 'job-bridge-e885b.firebasestorage.app',
    iosBundleId: 'com.example.jobBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8dAiBBG0pqFCX4E2mtOIs1RMIvhhNCI',
    appId: '1:1019752312959:ios:e79da494b69c31b6790f4a',
    messagingSenderId: '1019752312959',
    projectId: 'job-bridge-e885b',
    storageBucket: 'job-bridge-e885b.firebasestorage.app',
    iosBundleId: 'com.example.jobBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgwzijOz4JyymC9Fu1W1WcZc3Lg0UE4ig',
    appId: '1:1019752312959:web:58c55c47f2efb1ba790f4a',
    messagingSenderId: '1019752312959',
    projectId: 'job-bridge-e885b',
    authDomain: 'job-bridge-e885b.firebaseapp.com',
    storageBucket: 'job-bridge-e885b.firebasestorage.app',
  );
}
